(ns db.schema
  (:use [datomic.api :only [q db] :as d]))

(def schema
  [{:db/id #db/id[:db.part/db]
    :db/ident :schedule/broker,
    :db/valueType :db.type/string,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :schedule/product,
    :db/valueType :db.type/ref,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :schedule/management-fee,
    :db/valueType :db.type/bigdec,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :schedule/initial-fee,
    :db/valueType :db.type/bigdec,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :schedule/commission,
    :db/valueType :db.type/bigdec,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :schedule/minimum-investment,
    :db/valueType :db.type/bigdec,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :holding/owner,
    :db/valueType :db.type/ref,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :holding/product,
    :db/valueType :db.type/ref,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :holding/weight,
    :db/valueType :db.type/bigdec,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :holding/time,
    :db/valueType :db.type/instant,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :position/time,
    :db/valueType :db.type/instant,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :position/units,
    :db/valueType :db.type/bigdec,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :position/product,
    :db/valueType :db.type/ref,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :position/currency,
    :db/valueType :db.type/string,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :position/settlement-date,
    :db/valueType :db.type/instant,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :model/beta,
    :db/valueType :db.type/bigdec,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :model/product,
    :db/valueType :db.type/ref,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db
    :db/unique :db.unique/value}
   {:db/id #db/id[:db.part/db]
    :db/ident :model/hedged?,
    :db/valueType :db.type/boolean,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :model/approved?,
    :db/valueType :db.type/boolean,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :model/start,
    :db/valueType :db.type/instant,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :model/benchmark,
    :db/valueType :db.type/ref,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :model/r-square,
    :db/valueType :db.type/bigdec,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :model/end,
    :db/valueType :db.type/instant,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :synonym/name,
    :db/valueType :db.type/string,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db
    :db/unique :db.unique/value}
   {:db/id #db/id[:db.part/db]
    :db/ident :synonym/type,
    :db/valueType :db.type/keyword,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :synonym/is-bb-name?,
    :db/valueType :db.type/boolean,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :synonym/product,
    :db/valueType :db.type/ref,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :transaction/order-time,
    :db/valueType :db.type/instant,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :transaction/fill-time,
    :db/valueType :db.type/instant,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :transaction/trade-date,
    :db/valueType :db.type/instant,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :transaction/settlement-date,
    :db/valueType :db.type/instant,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :transaction/product,
    :db/valueType :db.type/ref,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :transaction/currency,
    :db/valueType :db.type/string,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :transaction/broker,
    :db/valueType :db.type/string,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db],
    :db/ident :transaction/units,
    :db/valueType :db.type/bigdec,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :transaction/value,
    :db/valueType :db.type/bigdec,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :transaction/price,
    :db/valueType :db.type/bigdec,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :transaction/internal-reference,
    :db/valueType :db.type/string,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :transaction/external-reference,
    :db/valueType :db.type/string,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :transaction/status,
    :db/valueType :db.type/string,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :transaction/primary-transaction,
    :db/valueType :db.type/ref,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :statement/order-time,
    :db/valueType :db.type/instant,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :statement/fill-time,
    :db/valueType :db.type/instant,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :statement/trade-date,
    :db/valueType :db.type/instant,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :statement/settlement-date,
    :db/valueType :db.type/instant,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :statement/product,
    :db/valueType :db.type/ref,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :statement/currency,
    :db/valueType :db.type/string,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :statement/broker,
    :db/valueType :db.type/string,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :statement/units,
    :db/valueType :db.type/bigdec,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :statement/value,
    :db/valueType :db.type/bigdec,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :statement/price,
    :db/valueType :db.type/bigdec,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :statement/internal-reference,
    :db/valueType :db.type/string,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :statement/external-reference,
    :db/valueType :db.type/string,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :statement/status,
    :db/valueType :db.type/string,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :statement/file-name,
    :db/valueType :db.type/string,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db],
    :db/ident :statement/matched-status,
    :db/valueType :db.type/string,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :product/type,
    :db/valueType :db.type/string,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :product/underlying,
    :db/valueType :db.type/string,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :product/underlying-product,
    :db/valueType :db.type/ref,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :product/geo-focus,
    :db/valueType :db.type/string,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :product/fund-type,
    :db/valueType :db.type/string,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :product/currency,
    :db/valueType :db.type/string,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :product/first-date,
    :db/valueType :db.type/string,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :product/expiry-date,
    :db/valueType :db.type/string,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :product/first-trade,
    :db/valueType :db.type/instant,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :product/expiry,
    :db/valueType :db.type/instant,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute
    :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :product/multiplier,
    :db/valueType :db.type/bigdec,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :product/single-priced?,
    :db/valueType :db.type/boolean,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :product/fut-gen-month,
    :db/valueType :db.type/string,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :product/fund-total-assets,
    :db/valueType :db.type/bigdec,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :product/fund-total-assets-currency,
    :db/valueType :db.type/string,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db],
    :db/ident :price/value,
    :db/valueType :db.type/bigdec,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :price/time,
    :db/valueType :db.type/instant,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :price/bat,
    :db/valueType :db.type/keyword,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :price/aspect,
    :db/valueType :db.type/keyword,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :price/product,
    :db/valueType :db.type/ref,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :price/source,
    :db/valueType :db.type/keyword,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :cash-position/units,
    :db/valueType :db.type/bigdec,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :cash-position/currency,
    :db/valueType :db.type/string,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :cash-position/category,
    :db/valueType :db.type/string,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}
   {:db/id #db/id[:db.part/db]
    :db/ident :cash-position/time,
    :db/valueType :db.type/instant,
    :db/cardinality :db.cardinality/one,
    :db.install/_attribute :db.part/db}])
